; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=AL
AppVerName=AL 1.0.7
AppPublisher=GarageInnovation
AppPublisherURL=http://www.garageinnovation.org/AL
AppSupportURL=http://www.garageinnovation.org/AL
AppUpdatesURL=http://www.garageinnovation.org/AL
DefaultDirName={pf}\AL
DefaultGroupName=AL
AllowNoIcons=yes
LicenseFile=C:\workspace\launcher\doc\license
Compression=lzma
SolidCompression=yes

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked
Name: "quicklaunchicon"; Description: "{cm:CreateQuickLaunchIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "C:\workspace\launcher\src\distAl\Al.exe"; DestDir: "{app}"; Flags: ignoreversion
Source: "C:\workspace\launcher\src\distAl\*"; DestDir: "{app}"; Flags: ignoreversion recursesubdirs
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[INI]
Filename: "{app}\Al.url"; Section: "InternetShortcut"; Key: "URL"; String: "http://www.garageinnovation.org/AL"

[Icons]
Name: "{group}\AL"; Filename: "{app}\Al.exe"
Name: "{group}\{cm:ProgramOnTheWeb,AL}"; Filename: "{app}\Al.url"
Name: "{userdesktop}\AL"; Filename: "{app}\Al.exe"; Tasks: desktopicon
Name: "{userappdata}\Microsoft\Internet Explorer\Quick Launch\AL"; Filename: "{app}\Al.exe"; Tasks: quicklaunchicon
Name: "{userstartup}\AL"; Filename: "{app}\Al.exe"

[Run]
Filename: "{app}\Al.exe"; Description: "{cm:LaunchProgram,AL}"; Flags: nowait postinstall skipifsilent

[UninstallDelete]
Type: files; Name: "{app}\Al.url"